### ISSUE TITLE
Unknown Issue

### ISSUE THREAD

**Issue by rouzbeh-afrasiabi** [rouzbeh-afrasiabi/MLOPS#8]
The experiment failed. Finalizing run...
Cleaning up all outstanding Run operations, waiting 300.0 seconds
5 items cleaning up...
Logging warning in history service: ERROR:: RunHistoryFinalization  failed. . Exception Details:Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_restclient/workspace_client.py", line 87, in _execute_with_arguments
    self._logger.debug("Experiment calls do not support old routes, calling experiment route")
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_restclient/clientbase.py", line 221, in _call_api
    back_off = 32
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_restclient/clientbase.py", line 274, in _execute_with_base_arguments
    while token and more_to_come is True:
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_restclient/clientbase.py", line 289, in _execute_func_internal
    del data_list[:]
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_restclient/clientbase.py", line 338, in _handle_retry
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_restclient/clientbase.py", line 287, in _execute_func_internal
    total_item_got += len(data_list)
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_restclient/operations/run_operations.py", line 376, in patch
    if response.status_code not in [200]:
azureml._restclient.models.error_response.ErrorResponseException: (UserError) Cannot create a workspace run document with runId=e2a760bb-4772-4e3e-8aaf-a616dbb67df0 and experimentId=e4b69d52-e4f8-4399-9a76-7e3783ac0494. A workspace run document already exists for experimentId=0fb624f6-a35d-43c2-a8f7-857823beced4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/mlops/azureml/7e1e2378-f310-4b16-87f6-66962a071e0d/mounts/workspaceblobstore/azureml/7e1e2378-f310-4b16-87f6-66962a071e0d/azureml-setup/context_manager_injector.py", line 99, in execute_with_context
    runpy.run_path(sys.argv[0], globals(), run_name="__main__")
  File "/opt/miniconda/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/opt/miniconda/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/opt/miniconda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "train.py", line 133, in <module>
    train()
  File "train.py", line 102, in train
    BFT.train(run,ml.bert_train_split,ml.bert_valid_split)
  File "/mnt/batch/tasks/shared/LS_root/jobs/mlops/azureml/7e1e2378-f310-4b16-87f6-66962a071e0d/mounts/workspaceblobstore/azureml/7e1e2378-f310-4b16-87f6-66962a071e0d/BertFineTuning/model.py", line 298, in train
    self.child_run.add_properties({"checkpoint_name":self.checkpoint_name})
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/core/run.py", line 1345, in add_properties
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_run_impl/run_history_facade.py", line 193, in add_properties
    self.metrics.log_accuracy_table(name, data_location=uri, description=description)
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_restclient/run_client.py", line 239, in patch_run
    if self.api_route == RunClient.OLD_ROUTE:
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_restclient/run_client.py", line 473, in _execute_with_run_arguments
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_restclient/workspace_client.py", line 89, in _execute_with_arguments
    is_paginated=True)
azureml._restclient.exceptions.ServiceException: ServiceException:
	Code: 409
	Message: (UserError) Cannot create a workspace run document with runId=e2a760bb-4772-4e3e-8aaf-a616dbb67df0 and experimentId=e4b69d52-e4f8-4399-9a76-7e3783ac0494. A workspace run document already exists for experimentId=0fb624f6-a35d-43c2-a8f7-857823beced4
	Details:

	InnerException{
    "additional_properties": {},
    "error": {
        "additional_properties": {},
        "code": "UserError",
        "message": "Cannot create a workspace run document with runId=e2a760bb-4772-4e3e-8aaf-a616dbb67df0 and experimentId=e4b69d52-e4f8-4399-9a76-7e3783ac0494. A workspace run document already exists for experimentId=0fb624f6-a35d-43c2-a8f7-857823beced4",
        "target": null,
        "details": [],
        "inner_error": null,
        "debug_info": null,
        "details_uri": null
    },
    "correlation": {
        "operation": "f10d1706-4a01-43fb-8471-a2e59f8a3380",
        "request": "yd6P9UpxJsg="
    },
    "environment": "eastus2",
    "location": "eastus2",
    "time": {}
}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/mlops/azureml/7e1e2378-f310-4b16-87f6-66962a071e0d/mounts/workspaceblobstore/azureml/7e1e2378-f310-4b16-87f6-66962a071e0d/azureml-setup/context_managers.py", line 153, in __exit__
    self.history_context.__exit__(*args)
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_history/utils/context_managers.py", line 57, in __exit__
  File "/opt/miniconda/lib/python3.6/contextlib.py", line 380, in __exit__
    raise exc_details[1]
  File "/opt/miniconda/lib/python3.6/contextlib.py", line 365, in __exit__
    if cb(*exc_details):
  File "/opt/miniconda/lib/python3.6/contextlib.py", line 284, in _exit_wrapper
    return cm_exit(cm, *exc_details)
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_history/utils/context_managers.py", line 165, in __exit__
    self.logger = logger
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_run_impl/run_base.py", line 159, in _kill
    module_logger.warn("Could not clean up all items! Data loss might occur!")
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_run_impl/run_base.py", line 169, in _cleanup
    def _cleanup(self, timeout):
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_run_impl/run_history_facade.py", line 565, in flush
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_restclient/metrics_client.py", line 232, in flush
    module_logger.warning("Invalid table, mixmatched column sizes, column of length {} "
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_common/async_utils/batch_task_queue.py", line 89, in flush
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_common/async_utils/task_queue.py", line 112, in flush
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_common/async_utils/task_queue.py", line 112, in <genexpr>
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_common/async_utils/async_task.py", line 59, in wait
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_common/async_utils/async_task.py", line 16, in basic_handler
  File "/opt/miniconda/lib/python3.6/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/opt/miniconda/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/opt/miniconda/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_restclient/metrics_client.py", line 261, in _log_batch
    out = {}
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_restclient/run_client.py", line 473, in _execute_with_run_arguments
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_restclient/workspace_client.py", line 89, in _execute_with_arguments
    is_paginated=True)
azureml._restclient.exceptions.ServiceException: ServiceException:
	Code: 400
	Message: (UserError) DataContainerId is not set for this run. Cannot post metrics with no DataContainerId
	Details:

	InnerException{
    "additional_properties": {},
    "error": {
        "additional_properties": {},
        "code": "UserError",
        "message": "DataContainerId is not set for this run. Cannot post metrics with no DataContainerId",
        "target": null,
        "details": [],
        "inner_error": null,
        "debug_info": null,
        "details_uri": null
    },
    "correlation": {
        "operation": "c0296fe2-98f8-4366-a466-3b54127dafe6",
        "request": "DGKHKR2Lrps="
    },
    "environment": "eastus2",
    "location": "eastus2",
    "time": {}
}

Traceback (most recent call last):
  File "train.py", line 133, in <module>
    train()
  File "train.py", line 102, in train
    BFT.train(run,ml.bert_train_split,ml.bert_valid_split)
  File "/mnt/batch/tasks/shared/LS_root/jobs/mlops/azureml/7e1e2378-f310-4b16-87f6-66962a071e0d/mounts/workspaceblobstore/azureml/7e1e2378-f310-4b16-87f6-66962a071e0d/BertFineTuning/model.py", line 298, in train
    self.child_run.add_properties({"checkpoint_name":self.checkpoint_name})
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/core/run.py", line 1345, in add_properties
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_run_impl/run_history_facade.py", line 193, in add_properties
    self.metrics.log_accuracy_table(name, data_location=uri, description=description)
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_restclient/run_client.py", line 239, in patch_run
    if self.api_route == RunClient.OLD_ROUTE:
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_restclient/run_client.py", line 473, in _execute_with_run_arguments
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_restclient/workspace_client.py", line 89, in _execute_with_arguments
    is_paginated=True)
azureml._restclient.exceptions.ServiceException: ServiceException:
	Code: 409
	Message: (UserError) Cannot create a workspace run document with runId=e2a760bb-4772-4e3e-8aaf-a616dbb67df0 and experimentId=e4b69d52-e4f8-4399-9a76-7e3783ac0494. A workspace run document already exists for experimentId=0fb624f6-a35d-43c2-a8f7-857823beced4
	Details:

	InnerException{
    "additional_properties": {},
    "error": {
        "additional_properties": {},
        "code": "UserError",
        "message": "Cannot create a workspace run document with runId=e2a760bb-4772-4e3e-8aaf-a616dbb67df0 and experimentId=e4b69d52-e4f8-4399-9a76-7e3783ac0494. A workspace run document already exists for experimentId=0fb624f6-a35d-43c2-a8f7-857823beced4",
        "target": null,
        "details": [],
        "inner_error": null,
        "debug_info": null,
        "details_uri": null
    },
    "correlation": {
        "operation": "f10d1706-4a01-43fb-8471-a2e59f8a3380",
        "request": "yd6P9UpxJsg="
    },
    "environment": "eastus2",
    "location": "eastus2",
    "time": {}
}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/mlops/azureml/7e1e2378-f310-4b16-87f6-66962a071e0d/mounts/workspaceblobstore/azureml/7e1e2378-f310-4b16-87f6-66962a071e0d/azureml-setup/context_manager_injector.py", line 210, in <module>
    execute_with_context(cm_objects, options.invocation)
  File "/mnt/batch/tasks/shared/LS_root/jobs/mlops/azureml/7e1e2378-f310-4b16-87f6-66962a071e0d/mounts/workspaceblobstore/azureml/7e1e2378-f310-4b16-87f6-66962a071e0d/azureml-setup/context_manager_injector.py", line 122, in execute_with_context
    print("Error occurred when setting run status to Finalizing: {}".format(ex))
  File "/mnt/batch/tasks/shared/LS_root/jobs/mlops/azureml/7e1e2378-f310-4b16-87f6-66962a071e0d/mounts/workspaceblobstore/azureml/7e1e2378-f310-4b16-87f6-66962a071e0d/azureml-setup/_vendor_contextlib2.py", line 393, in __exit__
    _reraise_with_existing_context(exc_details)
  File "/mnt/batch/tasks/shared/LS_root/jobs/mlops/azureml/7e1e2378-f310-4b16-87f6-66962a071e0d/mounts/workspaceblobstore/azureml/7e1e2378-f310-4b16-87f6-66962a071e0d/azureml-setup/_vendor_contextlib2.py", line 261, in _reraise_with_existing_context
    raise exc_details[1]
  File "/mnt/batch/tasks/shared/LS_root/jobs/mlops/azureml/7e1e2378-f310-4b16-87f6-66962a071e0d/mounts/workspaceblobstore/azureml/7e1e2378-f310-4b16-87f6-66962a071e0d/azureml-setup/_vendor_contextlib2.py", line 382, in __exit__
    if cb(*exc_details):
  File "/mnt/batch/tasks/shared/LS_root/jobs/mlops/azureml/7e1e2378-f310-4b16-87f6-66962a071e0d/mounts/workspaceblobstore/azureml/7e1e2378-f310-4b16-87f6-66962a071e0d/azureml-setup/_vendor_contextlib2.py", line 314, in _exit_wrapper
    return cm_exit(cm, *exc_details)
  File "/mnt/batch/tasks/shared/LS_root/jobs/mlops/azureml/7e1e2378-f310-4b16-87f6-66962a071e0d/mounts/workspaceblobstore/azureml/7e1e2378-f310-4b16-87f6-66962a071e0d/azureml-setup/context_manager_injector.py", line 49, in __exit__
    self.context_manager.__exit__(*exc_details)
  File "/mnt/batch/tasks/shared/LS_root/jobs/mlops/azureml/7e1e2378-f310-4b16-87f6-66962a071e0d/mounts/workspaceblobstore/azureml/7e1e2378-f310-4b16-87f6-66962a071e0d/azureml-setup/context_managers.py", line 153, in __exit__
    self.history_context.__exit__(*args)
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_history/utils/context_managers.py", line 57, in __exit__
  File "/opt/miniconda/lib/python3.6/contextlib.py", line 380, in __exit__
    raise exc_details[1]
  File "/opt/miniconda/lib/python3.6/contextlib.py", line 365, in __exit__
    if cb(*exc_details):
  File "/opt/miniconda/lib/python3.6/contextlib.py", line 284, in _exit_wrapper
    return cm_exit(cm, *exc_details)
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_history/utils/context_managers.py", line 165, in __exit__
    self.logger = logger
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_run_impl/run_base.py", line 159, in _kill
    module_logger.warn("Could not clean up all items! Data loss might occur!")
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_run_impl/run_base.py", line 169, in _cleanup
    def _cleanup(self, timeout):
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_run_impl/run_history_facade.py", line 565, in flush
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_restclient/metrics_client.py", line 232, in flush
    module_logger.warning("Invalid table, mixmatched column sizes, column of length {} "
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_common/async_utils/batch_task_queue.py", line 89, in flush
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_common/async_utils/task_queue.py", line 112, in flush
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_common/async_utils/task_queue.py", line 112, in <genexpr>
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_common/async_utils/async_task.py", line 59, in wait
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_common/async_utils/async_task.py", line 16, in basic_handler
  File "/opt/miniconda/lib/python3.6/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/opt/miniconda/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/opt/miniconda/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_restclient/metrics_client.py", line 261, in _log_batch
    out = {}
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_restclient/run_client.py", line 473, in _execute_with_run_arguments
  File "/opt/miniconda/lib/python3.6/site-packages/azureml/_restclient/workspace_client.py", line 89, in _execute_with_arguments
    is_paginated=True)
azureml._restclient.exceptions.ServiceException: ServiceException:
	Code: 400
	Message: (UserError) DataContainerId is not set for this run. Cannot post metrics with no DataContainerId
	Details:

	InnerException{
    "additional_properties": {},
    "error": {
        "additional_properties": {},
        "code": "UserError",
        "message": "DataContainerId is not set for this run. Cannot post metrics with no DataContainerId",
        "target": null,
        "details": [],
        "inner_error": null,
        "debug_info": null,
        "details_uri": null
    },
    "correlation": {
        "operation": "c0296fe2-98f8-4366-a466-3b54127dafe6",
        "request": "DGKHKR2Lrps="
    },
    "environment": "eastus2",
    "location": "eastus2",
    "time": {}
}

**Comment by rouzbeh-afrasiabi** [comment]
Was due to server issues
